# Replace placeholders like <MASTER_PUBLIC_IP> and the private key file paths with your actual details once Terraform executes
[master]
master_node ansible_host=<MASTER_PUBLIC_IP> ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/your-aws-key.pem

[workers]
worker1 ansible_host=<WORKER1_PUBLIC_IP> ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/your-aws-key.pem
worker2 ansible_host=<WORKER2_PUBLIC_IP> ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/your-aws-key.pem

[k8s_cluster:children]
master
workers
